### ISSUE TITLE
Semantics of `last_modified` unclear

### ISSUE THREAD

**Issue by reynir** [mirage/mirage-kv#41]
In the case where `last_modified` is called with a key that points to a dictionary it returns the latest `last_modified` value of its direct children.

https://github.com/mirage/mirage-kv/blob/1e3cdbd8167193de8a78b924fd3ccdf3f09c4afa/src/mirage_kv.mli#L159-L165

This definition is not well-founded as a dictionary's direct children could all be dictionaries themselves.

The interface doesn't explicitly disallow empty dictionaries although they can not be created directly. Depending on the implementation it could be achieved by setting a key `/empty/to-be-removed` and them removing `/empty/to-be-removed`. The interface doesn't mandate removing empty dictionaries resulting from `remove`.

A way out could be to default to `Ptime.min`, or leave it up to the implementation as some implementations have a concept of timestamps for dictionaries/directories.

**Comment by hannesm** [comment]
This is a great question:
- in the Unix setting, last-modified (mtime) of a directory is unrelated to its childs
- in the web (caldav/webdav) if I remember correctly there's discovery of modifications by looking at the last-modified of the calendar (direcyoy)
- in the web (canopy), the last modified of an index/listing page should be the last-modified of the latest children change

Caldav uses git, and it turns out the last-modified was rather expensive, thus caldav stores this entry as property and doesn't rely on the last-modified - reasoning was as well that removal of an entry wouldn't lead to an updated last-modified stamp.

So, back to your question, what about:
- define last-modified only on values?
- remove last-modified from the mirage-kv interface entirely?
- define last-modified of a dictionary as creation timestamp (and describe that users may want to track their own last-modified (removal / ..))

**Comment by reynir** [comment]
I think I lean more towards only defining last_modified on values. We could leave up to the implementations how to interpret last_modified on dictionaries. For some implementations a dictionaries have timestamps while in others a timestamp would have to be synthesized somehow. In the latter case I think it can make sense to allow implementations to return an error. The described behavior for dictionaries can be achieved by using `list` and iterating over the values (or all children) as the user sees fit.

As for the Unix implementation it looks like it doesn't implement the described behavior (where it's defined anyway).

I don't think it is very urgent to have it clarified.

**Comment by hannesm** [comment]
I agree with the proposed solution, and since `last_modified` may already return an error, it won't be too annoying for existing programs (that already need to deal with an error being returned).
